import { NextAuthProvider } from "@/app/providers";
import ProtectedRouteProvider from "@/app/components/next-auth/protected-route-provider";
import SessionClientProvider from "@/app/components/next-auth/session-client-provider";
import localFont from "next/font/local";
import Navbar from "@/app/admin/components/navbar/navbar";
export const metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

const akkurat = localFont({
  src: [
    {
      path: "../fonts/akkurat.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/akkurat-italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/akkurat-bold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "../fonts/akkurat-light.ttf",
      weight: "200",
      style: "light",
    },
  ],
  display: "swap",
});

// TODO: we shoudn't  access this
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={akkurat.className}>
        <SessionClientProvider>
          <ProtectedRouteProvider>
            <NextAuthProvider>
              <div>
                <Navbar />
                {children}
              </div>
            </NextAuthProvider>
          </ProtectedRouteProvider>
        </SessionClientProvider>
      </body>
    </html>
  );
}
